CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL,

    description VARCHAR(1000),

    price NUMERIC(15, 2) NOT NULL,

    stock_quantity INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_products_price_positive
        CHECK (price > 0),

    CONSTRAINT chk_products_stock_non_negative
        CHECK (stock_quantity >= 0)
);