spring.application.name=product-management

# Hibernate chỉ kiểm tra Entity và database có khớp nhau hay không
spring.jpa.hibernate.ddl-auto=validate

# Tránh truy vấn database ngoài Service/transaction
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration